# Generated by Haxe 3.3.0

import pandas as pandas_Pandas_Module


class Script:
    __slots__ = ()

    @staticmethod
    def main():
        housing_2013 = pandas_Pandas_Module.read_csv("../Hud_2013.csv")
        cols = ['AGE1', 'FMR', 'TOTSAL']
        filtered_housing_2013 = housing_2013[cols]
        filtered_housing_2013.hist(column='FMR', bins=20)
        print(str(filtered_housing_2013.head(5)))



Script.main()