# Generated by Haxe 3.3.0

import matplotlib.pyplot as matplotlib_pyplot_Pyplot_Module
import pandas as pandas_Pandas_Module
import seaborn as seaborn_Seaborn_Module


class Script:
    __slots__ = ()

    @staticmethod
    def main():
        seaborn_Seaborn_Module.set_style("dark")
        housing_2013 = pandas_Pandas_Module.read_csv("../Hud_2013.csv")
        cols = ['AGE1', 'FMR', 'TOTSAL']
        filtered_housing_2013 = housing_2013[cols]
        filtered_housing_2013.hist(column='FMR', bins=20)
        matplotlib_pyplot_Pyplot_Module.show()



Script.main()