# Generated by Haxe 3.3.0

import json as Json


class Script:
    __slots__ = ()

    @staticmethod
    def main():
        best_food_chains = ["Taco Bell", "Shake Shack", "Chipotle"]
        print(str(type(best_food_chains)))
        best_food_chains_string = Json.dumps(best_food_chains)
        print(str(type(best_food_chains_string)))
        print(str(type(Json.loads(best_food_chains_string))))
        _g = haxe_ds_StringMap()
        _g.h["Subway"] = 24722
        _g.h["McDonalds"] = 14098
        _g.h["Starbucks"] = 10821
        _g.h["Pizza Hut"] = 7600
        fast_food_franchise = _g
        fast_food_franchise_string = Json.dumps(fast_food_franchise)
        print(str(type(fast_food_franchise_string)))


class haxe_IMap:
    __slots__ = ()


class haxe_ds_StringMap:
    __slots__ = ("h",)

    def __init__(self):
        self.h = dict()




Script.main()