# Generated by Haxe 3.3.0

import pandas as pandas_Pandas_Module


class Script:
    __slots__ = ()

    @staticmethod
    def main():
        housing_2013 = pandas_Pandas_Module.read_csv("../Hud_2013.csv")
        cols = ['AGE1', 'FMR', 'TOTSAL']
        filtered_housing_2013 = housing_2013[cols]
        evaluated_row_numbers = filtered_housing_2013['AGE1'] > 0
        print(str(evaluated_row_numbers))



Script.main()