class Script:

	@staticmethod
	def main():
		cities_0 = "Albuquerque"
		cities_1 = "Anaheim"
		cities_2 = "Anchorage"
		cities_3 = "Arlington"
		cities_4 = "Atlanta"
		cities_5 = "Aurora"
		cities_6 = "Austin"
		cities_7 = "Bakersfield"
		cities_8 = "Baltimore"
		cities_9 = "Boston"
		cities_10 = "Buffalo"
		cities_11 = "Charlotte-Mecklenburg"
		cities_12 = "Cincinnati"
		cities_13 = "Cleveland"
		cities_14 = "Colorado Springs"
		cities_15 = "Corpus Christi"
		cities_16 = "Dallas"
		cities_17 = "Denver"
		cities_18 = "Detroit"
		cities_19 = "El Paso"
		cities_20 = "Fort Wayne"
		cities_21 = "Fort Worth"
		cities_22 = "Fresno"
		cities_23 = "Greensboro"
		cities_24 = "Henderson"
		cities_25 = "Houston"
		cities_26 = "Indianapolis"
		cities_27 = "Jacksonville"
		cities_28 = "Jersey City"
		cities_29 = "Kansas City"
		cities_30 = "Las Vegas"
		cities_31 = "Lexington"
		cities_32 = "Lincoln"
		cities_33 = "Long Beach"
		cities_34 = "Los Angeles"
		cities_35 = "Louisville Metro"
		cities_36 = "Memphis"
		cities_37 = "Mesa"
		cities_38 = "Miami"
		cities_39 = "Milwaukee"
		cities_40 = "Minneapolis"
		cities_41 = "Mobile"
		cities_42 = "Nashville"
		cities_43 = "New Orleans"
		cities_44 = "New York"
		cities_45 = "Newark"
		cities_46 = "Oakland"
		cities_47 = "Oklahoma City"
		cities_48 = "Omaha"
		cities_49 = "Philadelphia"
		cities_50 = "Phoenix"
		cities_51 = "Pittsburgh"
		cities_52 = "Plano"
		cities_53 = "Portland"
		cities_54 = "Raleigh"
		cities_55 = "Riverside"
		cities_56 = "Sacramento"
		cities_57 = "San Antonio"
		cities_58 = "San Diego"
		cities_59 = "San Francisco"
		cities_60 = "San Jose"
		cities_61 = "Santa Ana"
		cities_62 = "Seattle"
		cities_63 = "St. Louis"
		cities_64 = "St. Paul"
		cities_65 = "Stockton"
		cities_66 = "Tampa"
		cities_67 = "Toledo"
		cities_68 = "Tucson"
		cities_69 = "Tulsa"
		cities_70 = "Virginia Beach"
		cities_71 = "Washington"
		cities_72 = "Wichita"
		result = 0
		if (cities_2 == "Anchorage"):
			result = 1
		print(str(result))



Script.main()